const mv = document.querySelector("#mv");
const apr = document.querySelector("#apr");
const ele = document.querySelector("#ele");
const moveis = document.querySelector(".moveis");
const prod1 = document.querySelector(".prod1");
const prodtxt = document.querySelector(".prodtxt");
const prodimg = document.querySelector(".prod img");
const prod = document.querySelector(".prod");
const ld = document.querySelector(".ld");
const newp = document.querySelector(".new");
const pr = document.querySelector(".pr");
const prc = document.querySelector(".prc");
const com = document.querySelector(".com");
const txtp = document.querySelector(".txtp");
const prej = document.querySelector("#prej");
const vol = document.querySelector("#vol");
const dv = document.querySelector("#dv");
const nov = document.querySelector("#nov");
const sch = document.querySelector("#sch");
const myUL = document.querySelector("#myUL");
const myLI = document.querySelector("#myUL li");
const lg = document.querySelector(".lg");
const pr1 = document.querySelector("#pr1");
const desc = document.querySelector(".desc");
const img1 = document.querySelector("#img1");
const img2 = document.querySelector("#img2");
const img3 = document.querySelector("#img3");
const e1 = document.querySelector(".e1");
const e2 = document.querySelector(".e2");
const e3 = document.querySelector(".e3");
const e4 = document.querySelector(".e4");
const e5 = document.querySelector(".e5");
const exc = document.querySelector("#exc");
const coment = document.querySelector("#coment");
const cbtn = document.querySelector("#cbtn");
const cts = document.querySelector(".cts");
const nd = document.querySelector("#nd");
const e1r = document.querySelector(".e1r");
const e2r = document.querySelector(".e2r");
const e3r = document.querySelector(".e3r");
const e4r = document.querySelector(".e4r");
const e5r = document.querySelector(".e5r");
const re = document.querySelector(".re");
const avv = document.querySelector(".avv");
const prn = document.querySelector("#prn");
const cpr = document.querySelector("#cpr");
const quant = document.querySelector("#quant");
const vd = document.querySelector(".vd");
const btnspv = document.querySelector(".btnspv");
const prox = document.querySelector("#prox");
const volt = document.querySelector("#volt");
const pimg = document.querySelector("#pimg");
const lin = document.querySelector("#lin");
const drop = document.querySelector(".drop");
const cad = document.querySelector(".cad");
const nmu = document.querySelector(".nmu");
const droplg = document.querySelector(".droplg");
const nusu = document.querySelector("#nusu");
const desl = document.querySelector("#desl");
const usu = document.querySelector("#usu");

let parc;
let txtc;
let cmtr;
let ctxt;
let cps;
let cc = 0;
let rate1;
let rate2;
let rate3;
let rate4;
let rate5;
let dt;
let nota = 0;
let notact = 0;
let vds = 5;
